"use client";

import { Metadata } from "next";
import Image from "next/image";

import axios from "@/lib/axios";
import { useAuthStore } from "@/lib/zustand/AuthStore";

export default function Home() {
  const authenticated = useAuthStore((state) => state.authenticated);

  return (
    <main className="flex">
      {authenticated ? "YAY" : "NAY"}NAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
      <br />
      NAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAYNAY
    </main>
  );
}
